### PR TITLE
Special case some exception handling to provide more useful messages

### LINKED ISSUE #47: Clearer exceptions
We would like to implement some clearer exceptions to inform the user why exactly they triggered an internal error.

## Custom Exception Handlers
Make sure that the following exception handlers, if they change the response body payload for a given error code, get properly annotated so that the auto-generated documentation reflects that.

- [x] Create an exception handler to handle improper content-types and give the user a more informative message that they did not send a proper content-type. Keep in mind that some endpoints handle `application/json` and others handle `text/plain`

- [x] Create an exception handler to handle improper JSON in the request body.

### PR DESCRIPTION
**Pull request by 0teh**
Things to consider for the future:
- Always include an incidentId in the error response body, as another key?
- Tweak some errors to conform to REST standards, for example,
  report HttpMessageNotReadableExceptions as BAD_REQUESTs?

Fixes #47

### CODE REVIEW

File: src/main/kotlin/com/healthmetrix/labres/GlobalErrorHandler.kt [hunk 1]
```diff
@@ -13,17 +17,39 @@ class GlobalErrorHandler {
 
     @ExceptionHandler(Exception::class)
     @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
-    fun onException(exception: Exception): ResponseEntity<InternalServerError> {
+    fun onException(exception: Exception) = handle(exception)
+
+    @ExceptionHandler(HttpRequestMethodNotSupportedException::class)
+    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
```
Comment (khbnr) [inline src/main/kotlin/com/healthmetrix/labres/GlobalErrorHandler.kt:23]: Non of these should be `HttpStatus.INTERNAL_SERVER_ERROR` imo. Should be bad request

Comment (0teh) [reply src/main/kotlin/com/healthmetrix/labres/GlobalErrorHandler.kt:23]: Didn't want to change the external API in this convenience PR

Comment (khbnr) [reply src/main/kotlin/com/healthmetrix/labres/GlobalErrorHandler.kt:23]: I will create a ticket for it and approve then.
